site_name: What the hell is that?

theme:
  name: material
  features:
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences

repo_name: badasintended/wthit
repo_url: https://github.com/badasintended/wthit

docs_dir: src
edit_uri: tree/docs/src

nav:
  - Configurations:
    - Blacklisting Blocks and Entities: config/blacklisting.md

  - Plugin 101:
    - Getting Started: plugin/getting_started.md